name: macOS Monterey

on: [push, pull_request]

jobs:
  monterey:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Setup Qt
      run: curl -L https://github.com/rodlie/NatronPluginManager/releases/download/continuous/qtbase-5.15-static-macos.tar.bz2 --output qt.tar.bz2 && sudo tar xf qt.tar.bz2 -C /opt
    - name: Setup libzip
      run: curl -L https://github.com/rodlie/NatronPluginManager/releases/download/continuous/libzip-HighSierra.tar.gz --output libzip.tar.gz && sudo tar xf libzip.tar.gz -C /opt
    - name: Setup local
      run: sudo mkdir -p /opt/local/lib && sudo cp -a /opt/libzip/lib/* /opt/local/lib/
    - name: Build
      run: CMAKE=cmake sh share/macos.sh
    - name: Artifact
      run: sudo cp build/NatronPluginManager.dmg /opt/
    - uses: actions/upload-artifact@v2
      with:
        name: NatronPluginManager-${{github.sha}}-macOS
        path: /opt/NatronPluginManager.dmg
