name: Windows (MinGW)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: sudo mkdir -p /opt/mxe-NatronPluginManager && sudo chown 777 /opt/mxe-NatronPluginManager
    - name: SDK
      run: wget https://github.com/rodlie/NatronPluginManager/releases/download/continuous/mxe-NatronPluginManager-gcc7-qt515.tar.xz && tar xvf mxe-NatronPluginManager-gcc7-qt515.tar.xz -C /opt/mxe-NatronPluginManager/
    - name: Build
      run: bash share/mxe.sh
    - name: Artifact
      run: sudo cp build/NatronPluginManager.zip /opt/
    - uses: actions/upload-artifact@v2
      with:
        name: NatronPluginManager-${{github.sha}}-Windows-x64
        path: /opt/NatronPluginManager.zip
